# Generated by Django 2.2 on 2020-05-27 20:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Display Name')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Language code')),
                ('template', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.IntegerField(auto_created=True, default=0)),
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('QD', 'Queued'), ('CP', 'Completed'), ('ER', 'Error')], default='QD', max_length=3)),
                ('code', models.TextField()),
                ('stdin', models.TextField(blank=True)),
                ('output', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('exec_time', models.FloatField(null=True, verbose_name='Execution time')),
                ('created', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.Language')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.Room')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UJ', 'User Join'), ('UL', 'User Leave'), ('UR', 'User Run'), ('UM', 'User Message'), ('UJC', 'User Join Call'), ('ULC', 'User Leave Call'), ('LM', 'Log Message'), ('CO', 'Code Output')], max_length=3)),
                ('author_name', models.CharField(blank=True, max_length=20)),
                ('content', models.TextField(editable=False, max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
            ],
        ),
    ]
